/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2023 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include <stdio.h>
#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

__attribute__((naked)) void change_sp_to_psp(void)
{
	__asm volatile(".equ SRAM_END, (0x20000000 + (128 * 1024))");
	__asm volatile(".equ PSP_START, (SRAM_END - 512)");
	__asm volatile("LDR R0,=PSP_START");
	__asm volatile("MSR PSP,R0");
	__asm volatile("MOV R0,#0x02");
	__asm volatile("MSR CONTROL,R0");
	__asm volatile("BX LR");
}

uint8_t func_after(uint8_t a,uint8_t b)
{
	return (a+b);
}

uint8_t func_init(uint8_t c,uint8_t d)
{
	uint8_t ret = 0;

	ret = func_after(c,d);

	return (ret + c + d);
}
void generate_exception(void)
{
	__asm volatile("SVC #0x2");
}
int main(void)
{
	uint8_t return_val = 0;

	return_val = func_init(2,3);

	(void)return_val;
#if 0
	change_sp_to_psp();
    /* Loop forever */
	generate_exception();
#endif

	for(;;);
}

void SVC_Handler(void)
{
	printf(" in SVC_Handler\n");
}

