/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2023 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include <stdio.h>
#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

#define bit_band_base 0x20000000U
#define alias_base 0x22000000U
int main(void)
{
	uint8_t *ptr_bitband = NULL;
	uint8_t *ptr = (uint8_t *)0x20000200U;
	*ptr = 0xFFU;

	/* ALIAS ADDRESS = alias_base + (32*(bit_band_memory_addr - bin_band_base)) + bit*4 */
	/* Normal method to change bit 7th of 0x20000200 */
#if 0
	__asm volatile ("LDR R1,=#0x20000200");
	__asm volatile ("LDRB R0,[R1]");
	__asm volatile ("AND R0,R0,#0x7F");
	__asm volatile ("STRB R0,[R1]");

	*ptr &= ~(1 << 7);
#endif


	/* Bit-banding method to change bit 7th of 0x20000200 */
	ptr_bitband = (uint8_t *)(alias_base + (32*(0x20000200U - bit_band_base)) + 7 * 4);

	*ptr_bitband = 0;
#if 0
	__asm volatile ("LDR R1,=#0x20000200");
	__asm volatile ("LDRB R0,[R1]");
#endif
    /* Loop forever */
	for(;;);
}
