/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2023 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include <stdio.h>

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

#define IRQ_TIM2 28
#define IRQ_I2C1 31

void configure_priority_preempt_sub(uint8_t irq_number, uint8_t priority)
{
	uint32_t *pIPR = (uint32_t *)(0xE000E400 + ((irq_number / 4) * 0x04));
	uint8_t pos_offset = ((irq_number % 32) % 4) * 8;
	*pIPR &= ~(0xFF << pos_offset);
	*pIPR |= (priority << pos_offset);
}

int main(void)
{
	/* Enable and configure priority for TIM2 and I2C1 interrupt */

	/* Firstly, configure priority for interrupt */
	configure_priority_preempt_sub(IRQ_TIM2, 0xE0);
	configure_priority_preempt_sub(IRQ_I2C1, 0xC0);

	/* Mannual pend the pending bit for TIM2 and I2C1 ISPR */
	uint32_t *pISPR_TIM2 = (uint32_t *)(0xE000E200 + ((IRQ_TIM2 / 32) * 0x04));
	*pISPR_TIM2 = (1 << (IRQ_TIM2 % 32));

	/* Enable interrupt for TIM2 and I2C1 via NVIC ISER */
	uint32_t *pISER_I2C1 = (uint32_t *)(0xE000E100 + ((IRQ_I2C1 / 32) * 0x04));
	*pISER_I2C1 = (1 << (IRQ_I2C1 % 32));
	uint32_t *pISER_TIM2 = (uint32_t *)(0xE000E100 + ((IRQ_TIM2 / 32) * 0x04));
	*pISER_TIM2 = (1 << (IRQ_TIM2 % 32));
    /* Loop forever */
	for(;;);
}

void TIM2_IRQHandler(void)
{
	uint32_t *pISPR_I2C1 = (uint32_t *)(0xE000E200 + ((IRQ_I2C1 / 32) * 0x04));
	*pISPR_I2C1 = (1 << (IRQ_I2C1 % 32));
	printf("TIM2 \n");
	while(1);
}

void I2C1_EV_IRQHandler(void)
{
	printf("I2C1 \n");
	while(1);
}
