/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2023 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include <stdio.h>
#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

#define USGFAULT_OFFSET 18U
#define BUSFAULT_OFFSET 17U
#define MEMFAULT_OFFSET 16U
#define SHCRS_Base 0xE000ED24U

void UsageFault_Handler_c(uint32_t *p_baseStackFrame)
{
	register uint32_t msp_value __asm("r0");
	uint32_t* pMSP = (uint32_t *)msp_value;
	uint32_t *pUFSR = (uint32_t *)0xE000ED2A;
	printf("UsageFault_Handler\n");
	printf("UFSR = %lx\n",(*pUFSR) & 0xFFFFU);
	printf("The value of R0 = %lx\n",p_baseStackFrame[0]);
	printf("The value of R1 = %lx\n",p_baseStackFrame[1]);
	printf("The value of R2 = %lx\n",p_baseStackFrame[2]);
	printf("The value of R3 = %lx\n",p_baseStackFrame[3]);
	printf("The value of R12 = %lx\n",p_baseStackFrame[4]);
	printf("The value of LR = %lx\n",p_baseStackFrame[5]);
	printf("The value of PC = %lx\n",p_baseStackFrame[6]);
	printf("The value of XPSR = %lx\n",p_baseStackFrame[7]);
	while(1);
}

int main(void)
{
	/* Firstly, enable system exceptions */
	uint32_t *pSHCRS = (uint32_t *)SHCRS_Base;
	/* Enable usage fault exception */
	*pSHCRS |= (1 << USGFAULT_OFFSET);
	/* Enable bus fault exception */
	*pSHCRS |= (1 << BUSFAULT_OFFSET);
	/* Enable mem fault exception */
	*pSHCRS |= (1 << MEMFAULT_OFFSET);

#if 0
	/* Execute an undefined instruction, try executing instruction from peripheral region */
	uint32_t *pSRAM = (uint32_t *)0x20001000;
	*pSRAM = 0xFFFFFFFFU; /* undefined instruction */
	void (*some_addr) (void);
	some_addr = (void *)0x20001001; /* The last bit has to be 1 instead of 0 due to thumb state(must be 1 with arm cortex M4) */
	some_addr();
#endif

#if 1
	/* Divided by zero */
	/* Enable divided by zero trap in CCR */
	uint32_t *pCCR = (uint32_t *)0xE000ED14U;
	/* Enable -> fault */
	*pCCR |= (1 << 4);
	/* Disable -> no error */
	/* *pCCR &= ~(1 << 4); */
	uint8_t a = 5;
	a = a / 0;
	/* ->>>> if SHCSR for USGFAULT is disable, divided by 0 would lead to hardfault */
#endif


#if 0
	/* Executing SVC inside the SVC handler */
#endif

#if 0
	/* Executing SVC instruction inside the interrupt handler whose priority is same or lesser than SVC handler */
#endif

    /* Loop forever */
	for(;;);
}

__attribute__ ((naked)) void UsageFault_Handler(void)
{
	/* Extract the value of MSP when switching from thread mode to handler mode */
	__asm ("MRS r0,MSP");
	/* The content of the r0 becomes the argument 1 for the calee(UsageFault_Handler_c) */
	/* That's why the value of r0 will be captured in pBaseStackFrame */
	__asm ("B UsageFault_Handler_c");
}


void HardFault_Handler(void)
{
	printf("Hardfault_Handler\n");
	while(1);
}

void MemManage_Handler(void)
{
	printf("MemManage_Handler\n");
	while(1);
}

void BusFault_Handler(void)
{
	printf("BusFault_Handler\n");
	while(1);
}

void SVC_Handler(void)
{
	printf("SVC_Handler\n");
	while(1);
}
